#!/usr/bin/env python3
"""Ad text for the Darshan Saathi app campaign, by ad group (language).

Google Ads app campaigns take up to 5 headlines (30 characters each) and
up to 5 descriptions (90 characters each) per ad group. This script holds
the text, refuses anything over the limits, and writes ../ad-text.csv
and the tables in ../AD-TEXT.md.

Claims stay within what the app does: bookings only "at participating
temples", no "official" or "#1", no named temple that implies a tie-up.
"""
import csv
import os
import sys

HEADLINE_MAX, DESCRIPTION_MAX = 30, 90

GROUPS = {
    'English': {
        'headlines': [
            'Darshan Timings & Temple Guide',
            'Book Pujas & Sevas Online',
            'Hindu Festival Calendar 2026',
            'Your Temple Passport',
            'Free Temple Companion App',
        ],
        'descriptions': [
            'Darshan and aarti timings, dress code and directions for temples across India.',
            'Book archana and sevas at participating temples. Show the QR ticket at the counter.',
            'Every festival, Ekadashi and vrat for 2026–27, with a reminder before each one.',
            'Collect a stamp at every temple you visit and plan your next yatra.',
            "Give to a temple's hundi online, with a receipt. In English, Telugu, Hindi and more.",
        ],
    },
    'Telugu': {
        'headlines': [
            'దర్శన సమయాలు, ఆలయ సమాచారం',
            'పూజలు, సేవలు ఆన్‌లైన్ బుకింగ్',
            'పండుగల క్యాలెండర్ 2026',
            'మీ ఆలయ పాస్‌పోర్ట్',
            'దర్శన్ సాథీ – ఉచిత యాప్',
        ],
        'descriptions': [
            'ఆలయాల దర్శన, హారతి సమయాలు, దుస్తుల నియమాలు, దారి వివరాలు – అన్నీ ఒకే యాప్‌లో.',
            'పాల్గొనే ఆలయాల్లో అర్చన, సేవలు బుక్ చేసి కౌంటర్‌లో QR టికెట్ చూపించండి.',
            '2026–27 పండుగలు, ఏకాదశి, వ్రతాలు – ప్రతిదానికీ ముందే గుర్తు చేస్తాం.',
            'దర్శించిన ప్రతి ఆలయానికి ఒక ముద్ర. మీ తదుపరి యాత్రను ప్లాన్ చేయండి.',
            'ఆలయ హుండీకి ఆన్‌లైన్‌లో కానుక, రసీదుతో. తెలుగు, హిందీ, ఇంగ్లీష్‌లో.',
        ],
    },
    'Hindi': {
        'headlines': [
            'दर्शन का समय और मंदिर गाइड',
            'पूजा और सेवा ऑनलाइन बुक करें',
            'त्योहार कैलेंडर 2026',
            'आपका मंदिर पासपोर्ट',
            'दर्शन साथी – मुफ़्त ऐप',
        ],
        'descriptions': [
            'पूरे भारत के मंदिरों के दर्शन और आरती का समय, ड्रेस कोड और रास्ता।',
            'जुड़े हुए मंदिरों में अर्चना और सेवा बुक करें, काउंटर पर QR टिकट दिखाएँ।',
            '2026–27 के सभी त्योहार, एकादशी और व्रत, हर एक से पहले याद दिलाने के साथ।',
            'हर मंदिर दर्शन पर एक मुहर पाएँ और अपनी अगली यात्रा की योजना बनाएँ।',
            'मंदिर की हुंडी में ऑनलाइन दान करें, रसीद के साथ। हिंदी, तेलुगु, अंग्रेज़ी में।',
        ],
    },
}


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.dirname(here)
    errors = []
    rows = []
    for group, text in GROUPS.items():
        for kind, limit in (('headlines', HEADLINE_MAX), ('descriptions', DESCRIPTION_MAX)):
            items = text[kind]
            if len(items) > 5:
                errors.append(f'{group}: more than 5 {kind}')
            for n, line in enumerate(items, 1):
                if len(line) > limit:
                    errors.append(f'{group} {kind[:-1]} {n} is {len(line)} characters (max {limit}): {line}')
                rows.append([group, kind[:-1].capitalize(), n, line, len(line), limit])
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        return 1

    with open(os.path.join(out, 'ad-text.csv'), 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f)
        w.writerow(['Ad group', 'Type', 'No.', 'Text', 'Characters', 'Limit'])
        w.writerows(rows)

    md = ['# Ad text', '', 'Generated by `tools/copy.py` (it checks the limits). Paste each line into the ad group of the same language.', '']
    for group, text in GROUPS.items():
        md += [f'## {group}', '', '| | Headline (max 30) | Chars |', '|---|---|---|']
        md += [f'| {n} | {h} | {len(h)} |' for n, h in enumerate(text['headlines'], 1)]
        md += ['', '| | Description (max 90) | Chars |', '|---|---|---|']
        md += [f'| {n} | {d} | {len(d)} |' for n, d in enumerate(text['descriptions'], 1)]
        md += ['']
    with open(os.path.join(out, 'AD-TEXT.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(md))
    print(f'{len(rows)} lines, all within limits')
    return 0


if __name__ == '__main__':
    sys.exit(main())
